### ISSUE TITLE
Help with installling needed

### ISSUE THREAD

**Issue by netzproductions** [NoxxieNl/mailtopay-API#4]
Hello, would you please help me to get the API installed onto a shared hosting server?
I've run composer on a local php7.3-machine and then uploaded the vendor dir to the target server. When executing the example script, it dies with the following message:
 `Fatal error: Uncaught Error: Class 'Noxxie\Mailtopay\Endpoints\Paylinks' not found in test.php:11 Stack trace: #0 {main} thrown in /home/www/netzproductions/public/test2.php on line 11`

Relevant code:
````require __DIR__.'/vendor/autoload.php';

use Noxxie\Mailtopay\Endpoints\Paylinks;
use Noxxie\Mailtopay\Client;

$pay = new Paylinks;
````
I'd appreciate any help.

**Comment by NoxxieNl** [comment]
Hiya,

Where is your `vendor` directory located?

You need to include the `autoload.php` included within your vendor directory to allow the correct mapping of the classes.

if the `test2.php` is in your root directory then probably the following will work:
````php
require_once 'vendor/autoload.php';
````

**Comment by netzproductions** [comment]
Thanks for your fast response. The vendor dir is located in the same dir as the test file, giving no errors in the require statement itself, so that line shouldn't be the problem..

**Comment by NoxxieNl** [comment]
When you generated the autoloader the directory structure was the same?

**Comment by netzproductions** [comment]
I think so, generated it in my Mac's user dir and then transferred the whole vendor dir to the server.

**Comment by NoxxieNl** [comment]
Can you output your total php files you are using? (`index2.php`)

**Comment by netzproductions** [comment]
```
<?php

ini_set('display_errors','on');

require('vendor/autoload.php');

use Noxxie\Mailtopay\Endpoints\Paylinks;
use Noxxie\Mailtopay\Client;

$pay = new Paylinks;
$pay->setMethod('post')
    ->setConcerning('concerning')
    ->setLastname('lastname')
    ->setDebtornumber('debornumber')
    ->setUsername('username')
    ->setDueDate('2019-10-22')
    ->setInvoices([[
        'invoice_number'  =>  'test',
        'invoice_date'  =>  '2019-10-31',
        'invoice_amount'  =>  '1234',
        'invoice_description'  =>  'test'
    ]]);

$client = new Client('id', 'passphrase', 'base_uri', $pay);
$response = $client->execute();

// Fetch the paylink url.
$response->getPaylink();

?>
```

**Comment by NoxxieNl** [comment]
Well that looks fine to me.
You could try:

````php
use Noxxie\Mailtopay\Client;
use Noxxie\Mailtopay\Endpoints\Endpoint;
use Noxxie\Mailtopay\Endpoints\PayLinks;
use Noxxie\Mailtopay\Helpers\DefaultParameters;

require_once(__DIR__ . '/vendor/autoload.php');
Endpoint::registerDefaultValues('post',  DefaultParameters::postPaylinks());

$pay = new Paylinks;
$pay->setMethod('post')
	->setConcerning('concerning')
	->setLastname('lastname')
	->setDebtornumber('debornumber')
	->setUsername('username')
	->setDueDate('2019-12-28')
	->setInvoices([[
		'invoice_number'  =>  'test',
		'invoice_date'  =>  '2019-10-12',
		'invoice_amount'  =>  '12344',
		'invoice_description'  =>  'test'
    ]])
    ->setReturnUrl('https://test.nl/');
````

my test setup works likes this,
although I do not have access to a shared environment.

If that not works looks like it something with the difference between your local environment and your remote server.
